### ISSUE TITLE
IE11 上传不了图片

### ISSUE THREAD

**Issue by k79e** [qakcn/qchan#1]
上传之后那个 "+" 就消失了,然后啥都没了.

**Comment by k79e** [comment]
用了release里面的发现没问题.....

**Comment by qakcn** [comment]
只是IE11吗？这还在开发中所以不排除有各种问题。
如果你不是架设在内网或本地的，可以把地址发给我看看吗？
2014年11月1日 下午4:42于 "kxmp" notifications@github.com写道：

**Comment by k79e** [comment]
tuchuang.org用ie11上传不了.其他浏览器都可以..
ie11上传以后就这样了.
![2014-11-02_214507](https://cloud.githubusercontent.com/assets/6483602/4875431/9565664c-6296-11e4-99e9-b37215c61d92.png)

**Comment by qakcn** [comment]
你好，我试了一下确实是，暂未找到原因，如果你是要自己架设的话，可以把themes/default/main.php后面的zepto.min.js的那个script换成jquery的。
2014年11月2日 下午9:46于 "kxmp" notifications@github.com写道：
