### ISSUE TITLE
manage无法管理，所有上传的图片管理页都看不到，只能ftp管理

### ISSUE THREAD

**Issue by lwl12** [qakcn/qchan#2]
如标题。

**Comment by liwanglin12** [comment]
如果需要更多信息请发邮件到i@lwl12.com ~

**Comment by liwanglin12** [comment]
我补充一下，似乎我必须清空Cookies之后重新登录才会正常显示

**Comment by lwl12** [comment]
editthiscookies block “PHPSESSID”后正常

**Comment by StarryVoid** [comment]
能否请教一下editthiscookies block “PHPSESSID”这是什么原因？我也发生了这个状态（Chrome浏览器无法管理，Firefox可以）

**Comment by lwl12** [comment]
@StarryVoid 就是我用了 Editthiscookie这个Chrome扩展把PHPSESSID这个cookie屏蔽了就行了。。
不过我现在换 Chevereto 了

**Comment by StarryVoid** [comment]
我测试，必须把PHPSESSID这个值保持为空才可以。主要是不知道这个怎么去解决（和问题发生原因在哪）
Chevereto如果用的破解不会被封VPS么。。。

**Comment by lwl12** [comment]
首先 国内vps不管DMCA
其次 我上次和他们copyright邮箱撕过
其次 我和别人共享了正版
最后 Chevereto 最近出了 Free Version

StarrySky notifications@github.com于2016年9月7日周三 上午9:32写道：

**Comment by StarryVoid** [comment]
啊，，https://github.com/Chevereto/Chevereto-Free 。。。我看到了。。
之前眼拙。。谢谢您
