### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by tvvocold** [qakcn/qchan#3]
1，加入七牛云 SDK 实现CDN存储图片；
2，前台加入验证码或后台加入 ban ip功能防止Spam。

**Comment by qakcn** [comment]
云存储的支持是打算在qchan-plus中实现的。验证码的问题我研究一下。

**Comment by tvvocold** [comment]
赞！
可否加入自定义文件后缀？（允许上传其他类型文件）

**Comment by qakcn** [comment]
上传其他类型就不是图床了，是网盘了。

因为文件类型的验证比较复杂（并不是通过扩展名，而是通过MIME类型），要添加通过一种简单的机制来增加还不好实现。你要是想自己实现的话，我可以告诉你改哪些地方。
