### ISSUE TITLE
无法选择语言，已经后台登陆之后是空白的

### ISSUE THREAD

**Issue by kozora** [qakcn/qchan#5]
如题

**Comment by maysrp** [comment]
php.ini 中scandir()没有打开。
（lnmp默认是禁止scandir()）

**Comment by maysrp** [comment]
php.ini中 的scandir前的注释去掉就可以解决空白问题

**Comment by qakcn** [comment]
因为没有数据库，所以文件管理需要用scandir来扫描目录，没法扫描的话也没法用后台进行文件管理了。新版会加入数据库支持，请期待新版。

Xiaosea notifications@github.com于2015年10月14日 周三 11:46写道：
