### ISSUE TITLE
如何才能自动修改上传文件名？

### ISSUE THREAD

**Issue by fantastlcok** [qakcn/qchan#6]
请问
我应该修改哪个文件实现上传随机重命名？

**Comment by qakcn** [comment]
抱歉这么久才回复。

对于文件名的处理，都在`includes/functions.upload.php`中，有如下几处：

## 扩展名处理

主要是根据MIME类型统一扩展名，同时也是一个安全处理，避免非图片文件上传。

位置在第71行到96行，以及159到184行，两处的代码是一样的。

## 文件重命名处理

主要是针对重名文件，98行和187行都调用了·rename_if_exists·函数，该函数在249行到276行。

这里返回的就是最终的文件名，在下一行（99行和188行）就和上传目录拼接成最终的保存路径。

---

所以你要实现随机命名的话，可以修改·rename_if_exists·，该函数传入原文件名以及上传目录，返回新文件名（不包含上传目录）。

亦可修改98行和187行，调用你自己的文件名处理函数。在99行或188行之前处理文件名即可。
